spring:
  application:
    name: account.cmd
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bankingAccount
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 5000

